<?php

// Ouverture de la session pour l'affichage du layout
// Seulement si elle n'a pas été ouverte pécédemant
if (session_status() === PHP_SESSION_NONE) {
	session_start();
}

?>

<!DOCTYPE html>
<html>
<head>
	<title>Gestion - <?= $title ?? '' ?></title>

	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">

	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

</head>
<body>
	<header>
		<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
	        <div class="container-fluid">
	            <a class="navbar-brand" href="index.php">Gestion RH</a>
	            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
	                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
	                    aria-expanded="false" aria-label="Toggle navigation">
	                <span class="navbar-toggler-icon"></span>
	            </button>
	            <div class="collapse navbar-collapse" id="navbarSupportedContent">
	                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
	                    <li class="nav-item dropdown">
	                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
	                           data-bs-toggle="dropdown" aria-expanded="false">
	                            Gestion employés
	                        </a>
	                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
	                            <li><a class="dropdown-item" href="index.php">Tous les employés</a></li>
	                            <li><a class="dropdown-item" href="add_employee.php">Nouvel employé</a>
	                            </li>
	                        </ul>
	                    </li>
	                    <!-- Si la clé "auth" est présente dans $_SESSION => L'utilisateur est connecté -->
	                    <?php if (isset($_SESSION['auth'])): ?>
	                    	<li class="nav-item">
	                    		<a href="logout.php" class="nav-link">Déconnexion</a>
	                    	</li>
	                    <?php else: ?>
		                    <li class="nav-item">
		                    	<a href="register.php" class="nav-link">Inscription</a>
		                    </li>
		                    <li class="nav-item">
		                    	<a href="login.php" class="nav-link">Connexion</a>
		                    </li>
		                <?php endif ?>
	                </ul>
	                <?php if (isset($_SESSION['auth'])): ?>
	                	<span class="navbar-text me-3">Connecter :
	                		<?= $_SESSION['auth']['username'] ?>
	                	</span>
	                <?php endif ?>

	                <form class="d-flex">
	                    <input class="form-control me-2" type="search" placeholder="Rechercher" aria-label="Rechercher">
	                    <button class="btn btn-outline-danger" type="submit">Rechercher</button>
	                </form>
	            </div>
	        </div>
	    </nav>
	</header>

	<main class="container my-2">
		<?php require $template . '.phtml' ?>
	</main>
</body>
</html>