<h1>Connexion</h1>
	
	<form method="post" action="login.php">
		
		<?php if (isset($_SESSION['error'])): ?>
			<aside class="alert alert-danger">
				<?= $_SESSION['error'] ?>
				<!-- Affiche les deux error Nom d'utilisateur et Mot de passe si les deux sont fausses -- >
					<!-- <ul>
					<?php foreach ($SESSION['error'] as $error): ?>
						<li><?= $error ?></li>
					<?php endforeach ?>
					</ul> -->

				<!-- Suppression de l'erreur stockée après l'avoir affichée -->
				<?php unset($_SESSION['error']) ?>
			</aside>
		<?php endif ?>

		<div class="row g-3">
			<div class="col-md-6">
	        	<label for="username" class="form-label">Nom d'utilisateur :</label>
	        	<input type="text" class="form-control" id="username" name="username">
	      	</div>

	  		<div class="col-md-6">
	    		<label for="password" class="form-label">Mot de passe :</label>
	    		<input type="password" class="form-control" id="password" name="password">
	  		</div>

	  		<div class="col-12 d-flex justify-content-center">
	        	<button type="submit" class="btn btn-primary">Se connecter</button>
	      	</div>
      	</div>
	</form>