<!-- Création du formulaire d'inscription ppur register.php-->

<h1>Inscription</h1>

<form method="post" action="register.php">
	<div class="row g-3">
  		<div class="col-md-6">
    		<label for="username" class="form-label">Nom d'utilisateur :</label>
    		<input type="text" class="form-control" id="username" name="username">
  		</div>

      <div class="col-md-6">
        <label for="email" class="form-label">Email :</label>
        <input type="email" class="form-control" id="email" name="email">
      </div>

  		<div class="col-md-6">
    		<label for="password" class="form-label">Mot de passe :</label>
    		<input type="password" class="form-control" id="password" name="password">
  		</div>

      <div class="col-12 d-flex justify-content-center">
        <button type="submit" class="btn btn-primary">S'inscrire</button>
      </div>
  </div>
</form>